neveralone-chs-org/TestRay

lib/core/device.rb, tests/cases/case_helpers_never_alone.yaml, tests/cases/case_neveralone_login.yaml, tests/page_objects/dummy_page.yaml, tests/page_objects/never_alone_login_page.yaml
This PR has been created to automate the following test case: https://digitalscientists.atlassian.net/browse/CXTB-219
- Added tap and hide_keyboard funcionality.
- Created page object file for Never Alone app.
- Created file for Never Alone test helpers.
- Deleted Never Alone page objects from dummy page object file.
- Created test for log in process of Never Alone app.
=> test: Automate Never Alone login

tests/page_objects/never_alone_login_page.yaml
- deleted file that was duplicated.
=> fix: deleted duplicated file

tests/cases/case_care_platform_test.yaml, tests/page_objects/care_platform_page.yaml
This PR is for test case: https://digitalscientists.atlassian.net/browse/CXTB-90
Where we change status for the logged user, and check that we are unable to set "In Session" status manually.
=> Test Verify Status Indicator

tests/cases/case_care_platform_test.yaml, tests/page_objects/care_platform_page.yaml
CXTB-227 Account - Update info
=> Update My Account Info

lib/core/device.rb, tests/cases/case_neveralone_login.yaml, tests/cases/case_neveralone_schedule.yaml, tests/cases/case_neveralone_settings.yaml, tests/page_objects/never_alone_page.yaml
This PR has been created to automate this test case: https://digitalscientists.atlassian.net/browse/CXTB-10
This PR has the following changes:
- Created test for CXTB-10.
- Added page elements to the page.
- Created methods to to get tomorrow and yesterday time.
- Created custom method to assert that the past event went to the bottom on schedule page.
- Refactored previous test names.
- Updated previous test by deleting old method and fixed time format.
=> test: CXTB-226 full schedule display

tests/cases/case_care_platform_login.yaml, tests/page_objects/care_platform_page.yaml
Added a new care_platform_login yaml file. The test case is not 100% completed, it only goes until you have to verify the message in the mail.
=> 222 forgot password

tests/cases/case_employee_health_portal_account.yaml, tests/cases/case_employee_health_portal_singup.yaml, tests/cases/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
Added a note to test 215 and 216, they cover the same at the point they are.
Created navigation to My Account in the Employee Health Portal, and used it in test: CXTB-242
=> CXTB 233 Create navigation to My Account and using it in a test

tests/cases/case_care_platform_home.yaml
Adding the test case Account - Help
It changes the tab and verifies that the URL of the new tab has some expected parts. I'm not checking the whole URL because it may change in the future.
=> cxtb 237 Account - Help

tests/cases/case_employee_health_portal_account.yaml, tests/cases/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
Tried a lot of ways to make the phone number input empty, the only way it worked for me is to send 'backspace' key in a loop into the input.
=> CXTB-252 - EmployeeHealthPortal - View “My account” Information & Update Contact Number

tests/cases/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
Added a check for the filters in the Participants page.
=> Cxtb 251 participant directory filter

tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/providers_care_platform_page.yaml
This PR has been created to automate the following test case: 
https://digitalscientists.atlassian.net/browse/CXTB-191
- fixed a typo on an old page object and updated it on test.
- added page objects for employees on provider section.
- added test to cover CXTB-191.
=> test: CXTB-286 automate access employees directory and filter

tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/seniors_app/case_seniors_app_settings.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-23
- Added test to cover CXTB-23.
- Created corresponding page objects.
- Enhanced an existing page object and modified existing test.
=> test: CXTB-282 automate settings navigation

tests/cases/config.yaml, tests/cases/employee_health_portal/case_employee_health_portal_account.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
For this you need to sign up the dependent and add the network as trusted.
You will need it, as this run for both employee and dependent.
=> CXTB 241 - Employee Health Portal - Update Password

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-59
- Added test for CXTB-59.
- Added corresponding page objects.
- Added helper to log in using the secondary care partner.
=> test: CXTB-268 log out go off shift

tests/cases/config.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/page_objects/seniors_app_page.yaml
This PR has been created to automate the following test:
https://digitalscientists.atlassian.net/browse/CXTB-38
- Added test for CXTB-238.
- Added corresponding page objects.
- Fixed a duplicated value on config.yaml.
=> test: CXTB-246 automatically return to home after inactivity period

tests/cases/employee_health_portal/case_employee_health_portal_login.yaml, tests/page_objects/employee_health_portal_page.yaml
-changed file name 
-added page elements
=> CXTB-284 Forgot Password on Login Page

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/page_objects/care_platform_page.yaml
For this test you'll need to fill the data on the config file for carepartner 1 and 2.
Carepartner 2 is used to check the status of careparter 1.
=> CXTB-234 Log out - Stay on Shift

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-92
- Added test.
- Added corresponding page objects.
=> test: CXTB-274 automate access and review team availability

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-49
- Added test.
- Fixed a typo on existing test.
=> test: CXTB-244 alert and starting soon visuals

tests/cases/seniors_app/case_seniors_app_settings.yaml, tests/page_objects/seniors_app_page.yaml
This PR is to automate the following test case:
https://digitalscientists.atlassian.net/browse/CXTB-35
- Added test.
- Updated page objects.
- Updated existing test that used the page objects that were updated.
**NOTE:** this test will be merged but ticket will not be completed since it's going to be updated, JIRA ticket will have blocked status until updated. https://digitalscientists.atlassian.net/browse/CXTB-289
=> test: CXTB-289 wifi settings page

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
-Added the page objects
-Added test: TestParticipantRecordListing
This checks the record button funtionality and the record page elements, and navigation between tabs and subtabs.
=> CXTB-105 - Care Paretners - Participant Record from Listing

lib/core/device.rb, tests/cases/employee_health_portal/case_employee_health_portal_account.yaml, tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/page_objects/employee_health_portal_page.yaml, tests/page_objects/providers_care_platform_page.yaml
To run this test you must fill the config data for Employee user and Provider user. And, the provider should have all States on its account.
Added sleep command two times in the whole process to make it more reliable.
This PR test TC: https://digitalscientists.atlassian.net/browse/CXTB-86
=> CXTB-86 Employee Health Portal - Employee user call now

tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml
Adapting first test to a helper
Adding test for dependent
=> CXTB-88 Call Now as dependent

SETUP_IOS.md, lib/core/device.rb, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-31
- Added test.
- Added helpers.
- Updated readme on ios setup.
- Updated device.rb class to handle Appium 2.x server.
=> test: CXTB-294 appointment added notifications

tests/cases/providers_care_platform/case_providers_account.yaml
-To run this test you will need to fill the complete block corresponding to providers in the config file.
=> CXTB-201 Providers Manual Log Off And Stay on shift

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml
Test case automated:
https://digitalscientists.atlassian.net/browse/CXTB-19
- Added test.
- Added comment to helpers.
=> test: CXTB-309 future telehealth appointment cancel reschedule button

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
-Add test
-Add page selectors
-Made the call from senior
=> CXTB-93 Review Participant

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
This test include a wide check of the elements in the call portal
Doesn't include Medical transfer, that's covered in another test case
Requirements:
- Never Alone app and participant credentials
- Care Partner web app and care partner credentials
=> CXTB-95 Answer Call from Queue and Complete Session

tests/cases/seniors_app/case_seniors_app_schedule.yaml
Automated the following test case:
https://digitalscientists.atlassian.net/browse/CXTB-20
- Added test case.
=> test: CXTB-310 telehealth appointment missed window

lib/core/device.rb, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/cases/providers_care_platform/case_providers_account.yaml, tests/page_objects/employee_health_portal_page.yaml, tests/page_objects/providers_care_platform_page.yaml
Testing states credentials capabilities for providers, on answering calls.
No idea how to reproduce the "Special Needs Plan Certified" scenario.
=> CXTB-208 Provider credentials tests

lib/testray.rb, lib/utils/load.rb
=> Update execute_file command

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-56
- Added test.
- Added case helpers.
- Updated page objects.
=> test: CXTB-321 answer call from provider

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/seniors_app_page.yaml
Automated: 
https://digitalscientists.atlassian.net/browse/CXTB-129
- Added steps to existing test to comply with CXTB 129.
- Updated existing page objects.
=> test: CXTB-33 Automated Message Participant's Device

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-124
- Added test case.
- Updated page objects.
Proof of successful:
=> test: CXTB-342 call participants device call complete

.gitignore, CODEOWNERS, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/config.yaml, tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_prompts.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/sets/set_critical_workflow_tests.yaml
Adding git ignore changes
Adding CODEOWNERS files
Updating test names
Adding test set file for critical workflows
=> Adding CODEOWNERS And Test Sets files

README.md, lib/core/device.rb
- Updated documentation.
- Added "Page Object Model" section to index.
-  Fixed old binding on the index.
=> chore: CXTB-356 update documentation

tests/cases/seniors_app/case_seniors_app_home.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml, tests/sets/set_physical_devices_tests.yaml
- Added a test set for Physical Devices.
=> test: CXTB-354 added physical devices set

tests/cases/onboarders_care_platform/case_onboarders_care_platform_account.yaml, tests/page_objects/care_platform_page.yaml
Adding automated test of an onboarded account when accessing facilities.
=> Cxtb 261 automate onboarders access facilities directory%filter

tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml
=> CXTB-15 SNF - Confirmation Page

tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_physical_devices_tests.yaml
added TestSNFVerifyInAppOfflineBehavior to the corresponding test sets
=> test: added test to test sets

tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_notifications.yaml, tests/page_objects/skilled_nursing_facility_page.yaml
-Added page objects for notifications details modal.
-Added test
-Reused some page objects from Senior
=> CXTB-376 SNF - Verify notifications page

lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-126
- added test.
=> test: CXTB-373 call participant ignored

tests/cases/onboarders_care_platform/case_onboarders_care_platform_account.yaml
[https://digitalscientists.atlassian.net/browse/CXTB-256](url)
Successful run image:
=> Cxtb 145 click and view participant record from listing

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/seniors_app_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-128
- Added test.
=> test: CXTB-374 added call participant call missed

tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/page_objects/care_platform_page.yaml
Updated https://digitalscentists.atlassian.net/browse/CXTB-22 test case to comply with new changes
=> test: CXTB-334 update notifications test

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-131
- Added test.
=> test: CXTB-385 create event for participant

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/cases/helpers/case_helpers_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-132
- Added test case.
- Added helper.
Proof of Successful Run:
=> test: CXTB-386 edit event for partcipant

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-134
- Added test.
- Added page object.
=> test: CXTB-387 Automate delete event for participant

lib/core/device.rb, tests/cases/helpers/case_helpers_es_care_platform.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_care_platform_contact.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_home_page.yaml, tests/page_objects/idd_never_alone_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_physical_devices_tests.yaml
https://digitalscientists.atlassian.net/browse/CXTB-402
- added test.
- added page object.
- added test to corresponding sets.
- modified assert action so it can handle non utf characters like the ones returned by Never Alone on some components.
=> test: CXTB-361 in app offline mode iddes

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml
https://digitalscientists.atlassian.net/browse/CXTB-84
- Added test.
- Created and updated helper.
Proof Of Successful run:
=> test: CXTB-322 starting soon notification until survey completes

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml
https://digitalscientists.atlassian.net/browse/CXTB-381
- added test.
- updated helper.
=> test: CXTB-380 missed call prompt call back

tests/cases/config.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_care_platform_contact.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-414
- Added test.
- Updated page objects to match the AWS migration.
=> test: CXTB-398 Automate IDDApp - "Ignore Call” for Care Partner

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/cases/seniors_app/case_seniors_app_login.yaml, tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml, tests/cases/seniors_app/case_seniors_app_settings.yaml, tests/page_objects/care_platform_page.yaml
first part for the fixes for the following ticket: 
https://digitalscientists.atlassian.net/browse/CXTB-411
=> fix: CXTB-411 never alone care partner maintenance part 1

tests/cases/employee_health_portal/case_employee_health_portal_account.yaml, tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/cases/onboarders_care_platform/case_onboarders_care_platform_account.yaml, tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/providers_care_platform/case_providers_participants.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/employee_health_portal_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_SNF_not_physical.yaml
-Updating selectors for Onboarders
-Updating selectors for Employees
-Updating test according to new changes
-Remade test 161 for onboarders. It had participant's element tangled in a facility only test.
Employee folder:
Onboarder folder:
=> CXTB-412 Execute and Verify Onbaorders and EHP in AWS part1

lib/core/device.rb, tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_prompts.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/page_objects/providers_care_platform_page.yaml
- Checking for merge losses
- Changing cleaning method
=> Change on Providers cleaner

tests/cases/helpers/case_helpers_es_care_platform.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_home_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-428
- added test.
Proof Of Successful run:
=> test: CXTB-395 active appointment window when not joined prior idd

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/page_objects/care_platform_page.yaml
automated test case:
https://digitalscientists.atlassian.net/browse/CXTB-429
- added test
- added helper
- added page objects
=> test: CXTB-416 emergency services button visibility

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-440
- added test.
=> test: CXTB-423 edit or add contacts info

README.md, lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_account.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/page_objects/care_platform_page.yaml
-Created page objects for Participants tabs
-Created test for Editing Participant
-Change the name for the method we used to check or uncheck checkboxes.
-Added method: clear_field_by_backspace for when the clear_field and clear_field_js don't work
=> CXTB-424 Edit info for existing participant

lib/core/case_runner.rb, lib/core/device.rb
Updated actions to receive case information to be used when screenshots are taken.
=> Enhancing screenshot name for fail cases

tests/cases/care_partner_platform/case_care_platform_participants.yaml
-Added tag to corresponding test.
=> CXTB-421 Care Partner - Select Call in Queue and Get Call Answered Notification

README.md, lib/core/device.rb, tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml, tests/page_objects/providers_care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-441
- added test.
- added action.
- updated readme.
=> test: CXTB-433 call already answered

lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
-Adding test for Edit or Add Medication
-Adding page objects needed for the test
-Adding screenshot arguments in the device file
=> CXTB-426 Edit Participant Info - Edit or Add Medication Info

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_home.yaml
-Added test
-Updated expected class attributes
=> CXTB-404 ESCarePartner - Status Drop-down Options - Not on Active Call

tests/cases/providers_care_platform/case_providers_account.yaml, tests/page_objects/providers_care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-442
- added test.
Run proof:
=> test: CXTB-442 access and update credentials

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-446
- added test.
=> test: CXTB-444 edit or add allergies participant

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/page_objects/care_platform_page.yaml
automated test case:
https://digitalscientists.atlassian.net/browse/CXTB-449
- added test.
=> test: CXTB-448 edit or add emergency room admissions info

tests/cases/es_care_partner_platform/case_ch_care_platform_home.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_home.yaml, tests/cases/helpers/case_helpers_ch_care_platform.yaml, tests/page_objects/care_platform_page.yaml
Note: remember to make the trust network for users ES and CH of EasterSeals
-Added test for ES
-Added test for CH
=> CXTB-406 ES CarePartnerPlatform - Access and Review Team Member's Availability

tests/cases/providers_care_platform/case_providers_account.yaml, tests/page_objects/providers_care_platform_page.yaml
- Added test.
- Updated page object.
Success proof:
=> test: access and update credentials CCA status

tests/cases/providers_care_platform/case_providers_account.yaml, tests/page_objects/providers_care_platform_page.yaml
=> CXTB-454 Access and update ACO status credentials 

tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
=> Maintenance for employee tests

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
- Added test
- Added helper test
- Added Page Object
- Success of proof:
=> CXTB-279 automate participant profile review,edit or add vendor info

lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/employee_health_portal/case_employee_health_portal_login.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/cases/helpers/case_helpers_video_quality.yaml, tests/cases/seniors_app/case_seniors_app_account_statuses.yaml, tests/cases/seniors_app/case_seniors_app_home.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_only_web.yaml, tests/sets/set_physical_devices_tests.yaml
=> Maintenance NeverAloneMVP failed tests

README.md, lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
-Added test to change DNR and check its behavior
-Added page objects needed
=> CXTB-461 Edit Participant Info - Edit DNR Flag Field & Review Visuals

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-108
- added test.
=> test: CXTB-278 click and view follow up tickets

tests/cases/employee_health_portal/case_employee_health_portal_request_appointment.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
https://digitalscientists.atlassian.net/browse/CXTB-110
- added test.
- added a page object.
=> test: CXTB-456 request appointment for dependent minor

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
automated test case:
https://digitalscientists.atlassian.net/browse/CXTB-112
- added test.
- updated page object element.
- moved part of test to a helper case.
- added tests to web set.
=> test: CXTB-471 review add edit behavioral info

README.md, lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-116
- added test.
- updated page objects.
- updated helper.
- updated action on device.rb.
- added test to set.
=> test: CXTB-472 review add edit behavioral info participant pane

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml
=> CXTB 257 automate Onboarders review edit or add vendor info participant profile.

README.md, lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
-Added page elements
-Made test for TC: CXTB-121
-Added test to only_web set
-Added a new type to Device.rb
-Added documentation for the new Type
=> CXTB-473 CarePartnerPlatform - Participant Pane - Edit Insurance or Provider Information

tests/cases/employee_health_portal/case_employee_health_portal_account.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-531
- add test case
- add test to test set
=> test: CXTB-467 manually log out ehp

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-151
- add test
=> test: cxtb 258 onboarders review edit add behavioral info participant profile

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_only_web.yaml
-Added test for Care Partner and Onboarder
-Added tests to the web only set
=> CXTB-533 and CXTB-260 Participant Profile Edit Insurance or Provider Information

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-152
- add test
=> test: CXTB-259 onboarders review edit add behavioral info participant pane

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/config.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
automated test case:
https://digitalscientists.atlassian.net/browse/CXTB-536
- add test.
- add helper.
- add page objects.
- add test to set.
**NOTE:** use your phone number to test this pr
=> test: CXTB-463 call external 10 digit number without participant

tests/cases/config.yaml, tests/cases/facility_leadership_care_platform/case_facility_leadership_listing.yaml, tests/cases/helpers/case_helper_facility_leadership_care_platform.yaml, tests/page_objects/facility_leadership_page.yaml, tests/sets/set_only_web.yaml
-Adding page object
-Adding Config variables
-Test for 539
Note: you'll need to create your own user with Facility Leadership role, on Onboarders
=> CXTB-546 Facility Leadership - Access Facilities Directory and Filter

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/config.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
- Added two helpers for onboarders to make an user "Test", and to change it back
- Added a test for TC: https://digitalscientists.atlassian.net/browse/CXTB-537
=> CXTB-422 CarePartnerPlatform - Click and View Test Participant Visuals Listing, Profile and Call Portal

tests/cases/care_partner_platform/case_care_platform_login.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-369
- add test
- update helper
=> test: CXTB-570 Log In Button should be Limited to Single Click

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-562 OnboarderCarePartner - Change Status to Active for Existing Participant

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-564 Onboarders - Suspend Participant account

tests/cases/facility_leadership_care_platform/case_facility_leadership_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-550 Facility Leadership - Manually Log Out

tests/cases/onboarders_care_platform/case_onboarders_staff_members.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-503
- add test
=> test: CXTB-565 OnboardersCarePlatform - Access Staff Directory & Filter

tests/cases/facility_leadership_care_platform/case_facility_leadership_listing.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
=> CXTB-551 Facility Leadership - Click and View Facility Profile from Listing

tests/cases/es_care_partner_platform/case_ch_care_platform_home.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_home.yaml, tests/cases/helpers/case_helpers_ch_care_platform.yaml, tests/cases/helpers/case_helpers_es_care_platform.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-527
- add tests for CH and ES.
- add helpers.
- add test to sets.
- updated page objects.
=> test: CXTB-554 es manually logout stay on shift

tests/cases/es_care_partner_platform/case_ch_care_platform_calls.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_calls.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
-Added ES test
-Added CH test
-Added tests to set
=> CXTB-557 ESCarePartner Platform - Call Participants Device And Complete Call

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/cases/onboarders_care_platform/case_onboarders_staff_members.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-508
- add test
- update helper
=> test: CXTB-567 deactivate staff member staff pane

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/onboarders_care_platform/case_onboarders_care_platform_account.yaml, tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml
fixes for mobile tests from last regression run
=> Updating failing mobile tests

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_participants.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
-Added test
-Added test to critical set and non physical mobile test
-Added helper to Care Partner for making Medical Transfers
=> CXTB-592 Provider Care Platform - Answer call from Senior and navigate to info pages in platform while on call

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_account.yaml, tests/cases/config.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
- Added test
- Added test to sets
- Added name and lastname for Admin on call users 1 and 2, in the config file
=> CXTB-588 CXTB-589 Admin on Call - Log out manually

tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-599
- add test
=> test: CXTB-585 access staff directory admin on call

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_user_actions.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
- Added test
- Added test to set
- Took out some roles from helpers, to use them with more flexibility
Note: you'll need care partner, senior and Admin on call. Please have them set in the config file, and trusted in your network.
=> CXTB-587 Admin On Call - Refresh user account for calling

tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
https://digitalscientists.atlassian.net/browse/CXTB-511
- add test
=> test: CXTB-563 onboarder deactivate existing participant

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_account.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-605
- add test
=> test: CXTB-590 admin on call forgot password

tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/page_objects/admin_on_call_page.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
- Adding test
- Adding test to set
=> CXTB-586 Admin on Call - Refresh session for staff member from pane

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
https://digitalscientists.atlassian.net/browse/CXTB-610
- add test
- updated helpers
=> test: CXTB-580 select call already answered

tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml
- Added Test
- Added test to set
=> CXTB-596 Provider Care Platform - Return Missed SNF Call From Home

lib/core/device.rb, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-139
- add test
- add validation to the assert when a variable has invalid characters
Proof Of Sucessful run:
=> test: CXTB-594 provider ehp see call appear in queue

tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
- Removing work around for non required group id
- Added helper to check required data warning messages for Health Insurance
Note: this is used on other test than the Onboarder one. It was tested on all the other as well.
=> CXTB-609 OnboardersCarePlatform - Group ID should not be Required for Health Insurance Provider

tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/page_objects/onboarders_care_platform_page.yaml
-Adding steps to check for warnings on email input. (CHS-2420)
=> CXTB-608 OnboardersCarePlatform - Create Staff Member Not Showing Message if Fails Due to Duplicate Email

tests/cases/admin_on_call_care_platform/case_admin_on_call_queue.yaml, tests/cases/config.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/page_objects/admin_on_call_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml
https://digitalscientists.atlassian.net/browse/CHS-2515
- add test
- add helper
- add new desktop role
=> test: CXTB-611 admin on call should not auto answer calls

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/employee_health_portal_mobile_view/case_employee_health_portal_mobile_request_appointment.yaml, tests/cases/es_care_partner_platform/case_ch_care_platform_home.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml
=> Fixing care partner and provider navigation

tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml
- added fixes to care partner platform to comply with the new updates.
Failed tests on the report are coming from EMS known issues and QA environment known issues around the event list on the Call Portal.
=> test: CXTB-616 update care partner tests

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_account.yaml, tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_account.yaml, tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml
=> CXTB-615 Update Providers Tests

tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/cases/onboarders_care_platform/case_onboarders_facilities.yaml, tests/page_objects/onboarders_care_platform_page.yaml
-Added test
-Added page objects
Note: this is a test that creates devices for a facility, this devices can't be deleted by an users workflow, that might be a problem if the facilities have a max limit.
=> CXTB-613 Onboarders - Create New Facility Device and Verify Pre-delivery Status

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_user_actions.yaml, tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/onboarders_care_platform/case_onboarders_care_platform_account.yaml, tests/cases/onboarders_care_platform/case_onboarders_facilities.yaml, tests/page_objects/admin_on_call_page.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_only_web.yaml
Changes on the Admin on call test, following the last regression
=> CXTB-618 Update Admin on Call

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/onboarders_care_platform/case_onboarders_participants.yaml, tests/page_objects/onboarders_care_platform_page.yaml
-Checking there's no duplicated participant created, nor duplicated toast
=> CXTB-625 Update TestOnboarderCreateNewParticipant to check for duplicate participants

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_seniors_app.yaml, tests/cases/providers_care_platform/case_providers_call_history.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_only_web.yaml
-Can click and view provider call history and access call recordings
=> CXTB-595 Providers - Can Click and View Provider Call History And Access Call Recordings

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_account.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/es_care_partner_platform/case_ch_care_platform_follow_up_ticket.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_follow_up_ticket.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
-Checking for unassigned option for care partner follow-up
CHS
CH
ES
=> CXTB-628 CarePartner - No Options in Assigned To Drop-Down for Care Partner Follow-up

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_account.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/es_care_partner_platform/case_ch_care_platform_follow_up_ticket.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_follow_up_ticket.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/page_objects/care_platform_page.yaml
-Added look out for Rails Admin
=> CXTB-626 Admin on Call - Rails Admin Visible in Availability Listing

tests/cases/seniors_app/case_seniors_app_home.yaml, tests/sets/set_non_physical_mobile_tests.yaml
https://digitalscientists.atlassian.net/browse/CXTB-569
- add test
=> test: CXTB-569 ipad should not reset after care partner updates senior

tests/cases/care_partner_platform/case_care_platform_participants.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-156
- add test
=> test: CXTB-630 complete follow up ticket participant profile

lib/core/device.rb, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_only_web.yaml
=> CXTB-391-ProviderCarePlatform - Click and Review Facility Call History and Recordings

tests/cases/onboarders_care_platform/case_onboarders_staff_members.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_only_web.yaml
-Adding role filter
-Adding bug catcher
-Adding test for TC-506:
=> CXTB-631 OnboardersCarePlatform - Deactivate Staff Member Account for Care Platform - Staff Member Profile

tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_care_platform_contact.yaml, tests/cases/idd_never_alone_app/case_idd_never_alone_home_page.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/seniors_app/case_seniors_app_account_statuses.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/seniors_app/case_seniors_app_schedule.yaml, tests/page_objects/care_platform_page.yaml
this pr includes the changes needed to update/fix existing tests
=> fix: automation fixes

tests/cases/facility_leadership_care_platform/case_facility_leadership_home.yaml, tests/page_objects/facility_leadership_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml
Automated tets:
https://digitalscientists.atlassian.net/browse/CXTB-647
- add test
=> test: CXTB-637 see call appear on queue facility leadership

tests/cases/onboarders_care_platform/case_onboarders_staff_members.yaml, tests/sets/set_only_web.yaml
=> CXTB-632 Onboarders Care Platform - Reactivate Staff Member Account for Care Platform - Staff Member Profile

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_user_actions.yaml, tests/page_objects/admin_on_call_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-651 AdminOnCall - Refresh Nurse Account While On Call

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-642
- add test
=> test: CXTB-642 provider review info for existing facility

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml
automated ticket:
https://digitalscientists.atlassian.net/browse/CXTB-643
- add validation to existing test
- add missing tests to set
Proof Of Successful run:
=> test: CXTB-643 review participant info

tests/cases/es_provider_care_platform/case_ch_provider_care_platform_calls.yaml, tests/cases/es_provider_care_platform/case_es_provider_care_platform_calls.yaml, tests/cases/helpers/case_helper_es_care_platform_providers.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_es_provider_care_platform.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-638 ESProvider Care Platform - IDD - See Call Appear in Queue Assign and Review Details

tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-581 Provider Care Platform - Senior - See Call Appear in Queue, Assign and Review Details

tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-582 Provider Care Platform - IDD - See Call Appear In Queue Assign And Review Details

tests/cases/helpers/case_helpers_idd_never_alone.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-583 Provider Care Platform - IDD - Answer Call And Complete Session

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
-test for bugs
-added test to set
=> CXTB-641 Provider Care Platform - Forced Assessment View on Calls for Follow Ups Without Telehealth Request

tests/cases/es_care_partner_platform/case_ch_care_platform_participants.yaml, tests/cases/es_care_partner_platform/case_es_care_platform_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_es_care_partner_care_platform.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-556 ESCarePartner Platform - Send Message to Participant’s Device - Participant Profile

tests/cases/employee_health_portal_mobile_view/case_employee_health_portal_mobile_call.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/sets/set_employee_health_portal.yaml, tests/sets/set_only_web.yaml
=> CXTB-575 Employee Health Portal Mobile - Review Call History

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-178
- add test
=> test: CXTB-664 provider call participant and completes session

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/cases/onboarders_care_platform/case_onboarders_facilities.yaml, tests/cases/seniors_app/case_seniors_app_notifications.yaml, tests/cases/seniors_app/case_seniors_app_prompts.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/skilled_nursing_facility_page.yaml
=> Update tests to last release

tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_ch_care_platform.yaml, tests/cases/providers_care_platform/case_providers_account.yaml, tests/cases/providers_care_platform/case_providers_call_history.yaml, tests/cases/providers_care_platform/case_providers_employees.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_provider_care_platform.yaml
=> More updates for latest release

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-674 - Provider Care Platform - Call SNF Device For Issue Paused Task From Home - Ignored

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-166
- add test
=> test: CXTB-699 return missed seniors call from home answered

tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_status.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_nurse_facility_never_alone_app.yaml
=> CXTB-691 Skilled Nurse Facility - Pre-Delivery Account Status Visuals And Behavior

tests/cases/helpers/case_helpers_onboarders_care_platform.yaml, tests/cases/seniors_app/case_seniors_app_account_statuses.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_status.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_nurse_facility_never_alone_app.yaml
=> CXTB-694 Skilled Nurse Facility - Active Account Status Visuals

tests/cases/providers_care_platform/case_providers_account.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-697 ProvidersCarePlatform - Access and Review Team Members Availability

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-706
- add test
- updated helpers
=> test: CXTB-700 call seniors for issue paused answered

tests/cases/seniors_app/case_seniors_app_account_statuses.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_status.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_nurse_facility_never_alone_app.yaml
=> CXTB-693 Skilled Nurse Facility - Deactivated Account Status Visuals

lib/core/device.rb, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-698 ProviderCarePlatform - Return Missed SNF Call from Home (Ignored)

tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_status.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_nurse_facility_never_alone_app.yaml
https://digitalscientists.atlassian.net/browse/CXTB-331
- add test
=> test: CXTB-692 snf suspended account visuals

tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-707 ProviderCarePlatform - Call SNF Device for Follow-up Task from Home (Ignored)

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-713 Review Info for Existing Facility Device - Facility Profile

lib/core/device.rb, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> test: CXTB-701 return missed idd call ignore

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-721 Provider Care Platform - Access Facilities Directory and Filter

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/page_objects/care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
-Fix selectors
-Added test
-Added test to sets
=> CXTB-709 Provider Care Platform - Call Seniors Device for Issue Paused Task From Home Ignored

tests/cases/helpers/case_helpers_care_platform.yaml, tests/cases/providers_care_platform/case_providers_home.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-160
- add test
=> test: CXTB-734 provider return missed seniors call from home

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/page_objects/skilled_nursing_facility_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-748 Attempt an On-Demand Call to Facilitys Device (that is missed) Facility Pane

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-714 Can Click and View Facility Follow Up Tickets Information

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-176 Can Click and View Participant’s Emergency calls

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-738 Provider Attempt An OnDemand Call To Participants Device That Is Missed

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-733 SNF - Answer Call And Complete Session With Pause Issue

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-739 Send Message To Participants Device - Participant Profile

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-715 Provider Care Platform - Call Facility Device and Complete An On-Demand Call - Facility Profile

tests/cases/providers_care_platform/case_providers_participants.yaml, tests/sets/set_non_physical_mobile_tests.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-737 Attempt an On-Demand Call to Participant’s Device (that is Ignored)

tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/page_objects/care_platform_page.yaml, tests/page_objects/providers_care_platform_page.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
=> CXTB-741 Linked Participants Profile Page and Navigation

lib/core/device.rb, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/providers_care_platform/case_providers_facilities.yaml, tests/sets/set_only_web.yaml, tests/sets/set_provider_care_platform.yaml
https://digitalscientists.atlassian.net/browse/CXTB-777
- add test
- add helper
- updated action
=> test: CXTB-745 call external 10digit phone without facility

tests/cases/employee_health_portal/case_employee_health_portal_request_appointment.yaml, tests/sets/set_critical_workflow_tests.yaml, tests/sets/set_employee_health_portal.yaml, tests/sets/set_only_web.yaml
=> Cxtb 695 cancel upcoming appointment

tests/cases/admin_on_call_care_platform/case_admin_on_call_care_platform_user_actions.yaml, tests/cases/helpers/case_helper_care_platform_admin_on_call.yaml, tests/page_objects/admin_on_call_page.yaml, tests/sets/set_admin_on_call_care_platform.yaml, tests/sets/set_non_physical_mobile_tests.yaml
- Added Test
- Added Sets
Note: Searched staff by lastname only, since the search bar is not working with full names.
=> CXTB-755 Admin on Call - Refresh Session for Staff Member from Profile

.gitignore, README.md, lib/core/device.rb, lib/core/device_drivers.rb, tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/page_objects/onboarders_care_platform_page.yaml, tests/sets/set_admin_on_call_care_platform.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-779
- add test
- updated page object element
- added custom action
- added option to modify download path for chrome capabilities
- modified gitignore and readme
=> test: cxtb 757 access staff member listing and export audit log

lib/core/device.rb, tests/cases/care_partner_platform/case_care_platform_events.yaml, tests/cases/care_partner_platform/case_care_platform_home.yaml, tests/cases/care_partner_platform/case_care_platform_participants.yaml
Second part of fixes.
Changes that were not pushed on branch: CXTB-781-CarePartner-part2
=> CXTB-781 Care Partner fixes part2

tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_skilled_nursing_facility.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_requests.yaml, tests/cases/skilled_nurse_facility/case_skilled_nurse_facility_status.yaml
=> CXTB-788 SkillNurseFacility - Fix Automation Failures

tests/cases/admin_on_call_care_platform/case_admin_on_call_staff_listing.yaml, tests/cases/helpers/case_helpers_care_platform.yaml, tests/sets/set_admin_on_call_care_platform.yaml, tests/sets/set_non_physical_mobile_tests.yaml
=> CXTB-758 Admin on Call - Click and View Staff Members Follow-Up Tickets Information

lib/core/device.rb, tests/cases/employee_health_portal/case_employee_health_portal_call.yaml, tests/cases/employee_health_portal/case_employee_health_portal_request_appointment.yaml, tests/cases/employee_health_portal_mobile_view/case_employee_health_portal_mobile_call.yaml, tests/cases/employee_health_portal_mobile_view/case_employee_health_portal_mobile_my_info.yaml, tests/cases/employee_health_portal_mobile_view/case_employee_health_portal_mobile_request_appointment.yaml, tests/cases/helpers/case_helpers_care_platform_providers.yaml, tests/cases/helpers/case_helpers_employee_health_portal.yaml, tests/page_objects/employee_health_portal_page.yaml
- add method to clean appointments
- add sleeps
- add waits and wait_not_visible
=> fix: cxtb 785 fix ehp

tests/cases/admin_on_call_care_platform/case_admin_on_call_availability_and_notifications.yaml, tests/sets/set_admin_on_call_care_platform.yaml, tests/sets/set_only_web.yaml
https://digitalscientists.atlassian.net/browse/CXTB-759
- add test
=> test: cxtb 759 access and review team member availability admin on call

tests/cases/admin_on_call_care_platform/case_admin_on_call_call_queue_answer_call.yaml, tests/sets/set_admin_on_call_care_platform.yaml, tests/sets/set_non_physical_mobile_tests.yaml
https://digitalscientists.atlassian.net/browse/CXTB-792
- add test
=> test: cxtb 760 admin on call see call appear in queue review participant
